language: go

matrix:
  fast_finish: true
  include:
  - go: 1.10.x
  - go: 1.11.x
  - go: 1.12.x
  - go: 1.13.x

go_import_path: github.com/nmvalera/striped-mutex

script:
  - make vet
  - make fmt-check
  - make misspell-check
  - make run-coverage
  - make race